def test_assert_equal_1() -> None: ...
def test_assert_equal_2() -> None: ...
def test_assert_equal_3() -> None: ...
def test_assert_equal_4() -> None: ...
def test_assert_equal_5() -> None: ...
def test_assert_equal_6() -> None: ...
def test_assert_not_equal(a: int, b: int) -> None: ...
def test_assert_less(a: int, b: int) -> None: ...
def test_assert_less_equal(a: int, b: int) -> None: ...
def test_assert_greater(a: int, b: int) -> None: ...
def test_assert_greater_equal(a: int, b: int) -> None: ...
def test_assert_true(value: bool) -> None: ...
def test_assert_false(value: bool) -> None: ...
def test_assert_raises_1() -> None: ...
def test_assert_raises_2() -> None: ...
def test_assert_raises_3() -> None: ...
def test_assert_almost_equal(a: float, b: float) -> None: ...
def test_assert_almost_equal_2(a: float, b: float, err: float) -> None: ...
def test_assert_not_almost_equal(a: float, b: float) -> None: ...
def test_assert_not_almost_equal_2(a: float, b: float, err: float) -> None: ...
